### ISSUE TITLE
This is not an issue. Just Saying thanks for your effort.

### ISSUE THREAD

**Issue by gprabesh** [GuessWhatBBQ/FantechX9ThorDriver#1]
Although I was searching workarounds or X7 blast, this worked perfectly on my mouse without any hiccups. Thank you very much.

**Comment by GuessWhatBBQ** [comment]
I'm glad it works for you :)

**Comment by GuessWhatBBQ** [comment]
Although I find it very interesting that the same code works for a different mouse, which should have the same vendorID but a different productID, both of which are hardcoded in the code. Maybe they're using the same productID for both mice.

**Comment by gprabesh** [comment]
Looks like that. I downloaded mouse drivers of other fantech mice on windows and they were working fine. Looks like there is only slight hardware changes with other mices like design dpi etc.
