### ISSUE TITLE
It always says "Device not found. Try replugging"

### ISSUE THREAD

**Issue by 3omda1** [GuessWhatBBQ/FantechX9ThorDriver#11]

**Comment by GuessWhatBBQ** [comment]
Hey there. I am no longer working on this project anymore as I no longer have access to the mouse but I can still try to help.

Can you give me the output of `lsusb` ?

**Comment by 3omda1** [comment]
Hello, Thanks so much for your support
![image](https://github.com/GuessWhatBBQ/FantechX9ThorDriver/assets/68078588/c8780858-0c4e-4e32-bc5d-50bc4174ab8e)
Here is the output and mouse is connected and working fine

**Comment by GuessWhatBBQ** [comment]
Try changing line 8 in `driver_backend.py`

From:
```
        self.x9_productid = 0x1086  # productid
```
To:
```
        self.x9_productid = 0x0fc0  # productid
```

**Comment by GuessWhatBBQ** [comment]
Also if you added udev rules you'll have to make the same changes in `/etc/udev/rules.d/50-fantechdriver.rules`

If you want to risk it then you can try running the program as sudo instead

**Comment by 3omda1** [comment]
I have changed productid to be 0x0fc0 and it is worked fine with sudo without changing in the udev rules
Thanks so much for your help
you made my day :)

**Comment by GuessWhatBBQ** [comment]
You really should modify the udev rules as sudo might be unpredictable.

Anyways. Closing

**Comment by 3omda1** [comment]
I have changed it to be :
![image](https://github.com/GuessWhatBBQ/FantechX9ThorDriver/assets/68078588/212100d5-cd53-44e8-90d5-73560ba33080)

and still gives me this error
![image](https://github.com/GuessWhatBBQ/FantechX9ThorDriver/assets/68078588/543bd275-7453-40c0-acc2-599505f27408)

**Comment by GuessWhatBBQ** [comment]
Make sure you restart your system for it to take effect. Also make sure you're part of the users group

**Comment by 3omda1** [comment]
Yes I did, are the configuration I shared are correct ?

**Comment by GuessWhatBBQ** [comment]
Yes they should be. Output of `groups` ?

**Comment by 3omda1** [comment]
![image](https://github.com/GuessWhatBBQ/FantechX9ThorDriver/assets/68078588/8b410825-03db-48da-8d2d-0b7608bd768b)

Here it is, and thanks so much for your support

**Comment by GuessWhatBBQ** [comment]
Well then I'm at a loss as to why it doesn't work for you
