### ISSUE TITLE
Install is not working, but I can't figure out why

### ISSUE THREAD

**Issue by Dtravler** [GuessWhatBBQ/FantechX9ThorDriver#2]
I tried to load your driver into Ububtu 20.04, But got the following error,

`robert@robert-N46VZ:~$ pip download git+https://github.com/GuessWhatBBQ/FantechX9ThorDriver.git
Collecting git+https://github.com/GuessWhatBBQ/FantechX9ThorDriver.git
  Cloning https://github.com/GuessWhatBBQ/FantechX9ThorDriver.git to /tmp/pip-req-build-c8xe3ox7
  Running command git clone -q https://github.com/GuessWhatBBQ/FantechX9ThorDriver.git /tmp/pip-req-build-c8xe3ox7
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-c8xe3ox7/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-c8xe3ox7/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-57zr7d6p
         cwd: /tmp/pip-req-build-c8xe3ox7/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.8/tokenize.py", line 392, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-c8xe3ox7/setup.py'
    ----------------------------------------
WARNING: Discarding git+https://github.com/GuessWhatBBQ/FantechX9ThorDriver.git. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

any clue what goes wrong here and how to solve it?

**Comment by GuessWhatBBQ** [comment]
Could you try cloning using git directly ? It looks like an issue with pip to me and since I've never used pip for cloning I cant really help you

basically run
`git clone https://github.com/GuessWhatBBQ/FantechX9ThorDriver.git`
