### ISSUE TITLE
usb.core.USBError: [Errno 13] Access denied (insufficient permissions) [SOLVED] 

### ISSUE THREAD

**Issue by iqbalfaris24** [GuessWhatBBQ/FantechX9ThorDriver#3]
do you guys know how to solve it?

**Comment by GuessWhatBBQ** [comment]
I'm sorry, I should've included this in the README but python needs access to the usb ports, which only works if you have appropriate UDEV rules set up ([see here](https://wiki.archlinux.org/index.php/udev#Accessing_firmware_programmers_and_USB_virtual_comm_devices)) or run the program as root (the easiest way but not recommended).

The easy way being:

```sudo python driver_frontend.py```

but again I absolutely dont recommend this as running as root is hardly ever recommended.

**Comment by iqbalfaris24** [comment]
I use the root method because I can't understand how to add udev because I'm a new user Xd, but the program is running well and Thank you very very very much for creating this program!
![image](https://user-images.githubusercontent.com/77491337/114318501-7302c500-9b37-11eb-8966-72be1047cbfa.png)

**Comment by GuessWhatBBQ** [comment]
Wow you're gtk theme is really pretty. Also I'm glad it works for you :)

**Comment by iqbalfaris24** [comment]
hahaha just downloaded theme Xd

by the way I'm really curious how can I add udev, do you have any references (video is better)?

**Comment by GuessWhatBBQ** [comment]
Could you try adding
```
SUBSYSTEMS=="usb", ATTRS{idVendor}=="18f8", ATTRS{idProduct}=="1086", GROUP="users", MODE="0660"
```
to a file like this `/etc/udev/rules.d/50-fantechdriver.rules` ?

or in one command
```
echo "SUBSYSTEMS==\"usb\", ATTRS{idVendor}==\"18f8\", ATTRS{idProduct}==\"1086\", GROUP=\"users\", MODE=\"0660\"" | sudo tee /etc/udev/rules.d/50-fantechdriver.rules
```
Either way you do it you'll need to restart for it to take effect

This will basically allow every user in the `users` group to access your usb mouse without having to use sudo

**Comment by iqbalfaris24** [comment]
I already added
![image](https://user-images.githubusercontent.com/77491337/114319854-74cf8700-9b3d-11eb-9586-a31243b2f139.png)

but the error message still appears
![image](https://user-images.githubusercontent.com/77491337/114319895-a2b4cb80-9b3d-11eb-8a26-a9396b400c85.png)

**Comment by GuessWhatBBQ** [comment]
You also need to restart, sorry forgot to mention that

**Comment by iqbalfaris24** [comment]
I just finished rebooting but.. same:( nothing changes :(
![image](https://user-images.githubusercontent.com/77491337/114320231-32a74500-9b3f-11eb-8c11-a58e73934053.png)

**Comment by GuessWhatBBQ** [comment]
Interesting.

Could you run
`cat /etc/udev/rules.d/50-fantechdriver.rules`
and
`groups`
and send the output here ?

**Comment by iqbalfaris24** [comment]
![image](https://user-images.githubusercontent.com/77491337/114320351-d1cc3c80-9b3f-11eb-95f2-1acbe1312994.png)
I'm really sorry for disturbing your time btw :(

**Comment by GuessWhatBBQ** [comment]
also `lsusb`

**Comment by iqbalfaris24** [comment]
this one?
![image](https://user-images.githubusercontent.com/77491337/114320442-296aa800-9b40-11eb-8a29-01823aef263b.png)

**Comment by GuessWhatBBQ** [comment]
You're actually helping out other users so you're doing people a favor

**Comment by GuessWhatBBQ** [comment]
Also run the `groups` command please

**Comment by iqbalfaris24** [comment]
sorry I don't understand opening these groups :(

**Comment by iqbalfaris24** [comment]
this one? 
![image](https://user-images.githubusercontent.com/77491337/114320611-d9401580-9b40-11eb-9ee0-a3a052e30a4f.png)

**Comment by GuessWhatBBQ** [comment]
just type `groups` in your terminal and send the output here, it'll tell me know which groups your user is a part of. The rules that you added only work for users of a certain group called `users` so if you're not a part of that group it wont work

**Comment by GuessWhatBBQ** [comment]
> this one?
> ![image](https://user-images.githubusercontent.com/77491337/114320611-d9401580-9b40-11eb-9ee0-a3a052e30a4f.png)

you have a type, you missed the "s" in groups

**Comment by iqbalfaris24** [comment]
under that error I have corrected it

**Comment by GuessWhatBBQ** [comment]
Alright so you dont have a group called users, now there's 2 ways to go, you could create a group called users and add yourself to that group or you could modify the rules file to give permission to the group iqbal which is linked to your username I'm assuming.

the first method would be like this
```
    sudo groupadd users
    sudo usermod -a -G users your_user_name
```
and is what I would recommend

**Comment by iqbalfaris24** [comment]
I tried the first method and got a message like this

in first command 
iqbal@Flexy:~$ sudo groupadd users
groupadd: group 'users' already exists

and the second command
![image](https://user-images.githubusercontent.com/77491337/114320955-c0386400-9b42-11eb-8ddd-c8ba12be99be.png)

**Comment by iqbalfaris24** [comment]
and I have tried the second method but still the error message as before
![image](https://user-images.githubusercontent.com/77491337/114321207-d692ef80-9b43-11eb-977f-e80479539f38.png)

**Comment by GuessWhatBBQ** [comment]
Did you restart again ?

**Comment by iqbalfaris24** [comment]
UPDATE!

I forgot to reboot after doing the second method, now the program runs fine without any error messages and without the root method of course

![image](https://user-images.githubusercontent.com/77491337/114321487-2f16bc80-9b45-11eb-9153-eb2c89ad512e.png)


but the first method still doesn't work I will find a way and if it works I will share it here

**Comment by iqbalfaris24** [comment]
thank you buddy for helping me and giving new knowledge to me! I appreciate that! Thankyou so much man....

**Comment by GuessWhatBBQ** [comment]
That's great!
I think I messed up on the second command and it should've been

`sudo usermod -a -G users your_user_name`

My bad

**Comment by iqbalfaris24** [comment]
error message still appears :(
I don't know why it seems like my linux is the problem ..
![image](https://user-images.githubusercontent.com/77491337/114321723-69cd2480-9b46-11eb-8573-80942dbef071.png)

**Comment by GuessWhatBBQ** [comment]
Isnt your username iqbal ?

**Comment by iqbalfaris24** [comment]
I tried the username iqbal but no message at all and just a new line. what exactly is the command's function?
![image](https://user-images.githubusercontent.com/77491337/114321821-08598580-9b47-11eb-8f82-03cc636d555d.png)

**Comment by GuessWhatBBQ** [comment]
So the command worked, now run `groups` to check whether you've been added to the group

**Comment by iqbalfaris24** [comment]
there is no difference in the output?
![image](https://user-images.githubusercontent.com/77491337/114321855-46ef4000-9b47-11eb-8069-cf46d3d6f77e.png)

**Comment by GuessWhatBBQ** [comment]
You probably need to logout and login, could also restart for good measure

**Comment by iqbalfaris24** [comment]
hahaah that's right! the lesson to be learned is "don't forget to reboot after making changes" Xd
![image](https://user-images.githubusercontent.com/77491337/114322012-2ffd1d80-9b48-11eb-841a-e6ee86a50eeb.png)



> You probably need to logout and login, could also restart for good measure

**Comment by GuessWhatBBQ** [comment]
Ah now having "users" in the udev rules file should also work

**Comment by iqbalfaris24** [comment]
Thank you for making the program and helping me! I hope that those who have the same error message can be helped by this conversation

**Comment by GuessWhatBBQ** [comment]
I'll be deleting all the troubleshooting stuff from the issue and only keep the important parts

**Comment by iqbalfaris24** [comment]
> Ah now having "users" in the udev rules file should also work

right, I will change it after this

**Comment by iqbalfaris24** [comment]
> I'll be deleting all the troubleshooting stuff from the issue and only keep the important parts

looks good..

**Comment by GuessWhatBBQ** [comment]
Actually I'll just close this and edit the README

**Comment by iqbalfaris24** [comment]
> Actually I'll just close this and edit the README

that's better, go ahead if it's good to do
