### ISSUE TITLE
ModuleNotFoundError: No module named 'usb

### ISSUE THREAD

**Issue by hellwraiz** [GuessWhatBBQ/FantechX9ThorDriver#6]
I am running `python3 driver_frontend.py`, but it gives me an error: 

`File "/home/olehgrypas/FantechX9ThorDriver/driver_frontend.py", line 1, in <module>`
`    import driver_backend`
`  File "/home/olehgrypas/FantechX9ThorDriver/driver_backend.py", line 1, in <module>`
`    import usb.core`
`ModuleNotFoundError: No module named 'usb'`

So naively I tried `pip install usb`, which installed something, but apparently not what I need.

**Comment by hellwraiz** [comment]
I had this issue when trying to open the app in a virtual env, when I stopped the env it all worked.

**Comment by GuessWhatBBQ** [comment]
`pip install usb` doesnt install the library that's used by the project as we use `pyusb` instead. I'm glad it's working now :)
