### ISSUE TITLE
I can use my fantech vx7 on linux using this

### ISSUE THREAD

**Issue by theace1** [GuessWhatBBQ/FantechX9ThorDriver#7]
may i fork this project to another repo?, i mean i modified the code then give the credit to you

**Comment by GuessWhatBBQ** [comment]
The project is licensed under GPL V3. ie it is free software. You can do whatever you want with it as long as any new published version is also free and licensed under a compatible license. Happy hacking :).

Edit: As far as credit goes your modifications are credited to you and the original code I wrote is credited to me by default, so it's not something I'm at all worried about.
