### ISSUE TITLE
Mouse not detected [Solved]

### ISSUE THREAD

**Issue by melcone** [GuessWhatBBQ/FantechX9ThorDriver#8]
I did the installations but when I run the command "python driver_frontend.py "; it says "Device not found. Try replugging". I already tried replugging but it still won't work. I use manjaro kde plasma.
![Screenshot_20220214_121651](https://user-images.githubusercontent.com/98726565/153799238-6fa9174d-b383-4196-ae20-2caa643472c6.png)

**Comment by GuessWhatBBQ** [comment]
It seems your device has a different productid (the 4 digit number after 18f8: ) than the one I had. It's 0fc0 in your case and was 1086 in mine.
Try and change the product id in line 8 of the python_backend.py file like this:
```
self.x9_productid = 0x0fc0
```

Also are you sure you're using the fantech x9 thor mouse and not a different model ?

**Comment by melcone** [comment]
It worked! And yes I am using the Fantech X9 Thor mouse, but this popped up;
![Screenshot_20220217_212547](https://user-images.githubusercontent.com/98726565/154491014-5b89c4a0-4534-42e0-a0b2-b6ff4315b057.png)

**Comment by GuessWhatBBQ** [comment]
Did you run the command that creates a udev rule ? Since your product id is different you'll have to run something like this instead.

```
echo "SUBSYSTEMS==\"usb\", ATTRS{idVendor}==\"18f8\", ATTRS{idProduct}==\"0fc0\", GROUP=\"users\", MODE=\"0660\"" | sudo tee /etc/udev/rules.d/50-fantechdriver.rules
```

**Comment by GuessWhatBBQ** [comment]
Also this is bad practice but did you try running as root using sudo ? That shouldn't have any permission issues. Not a permanent solution of course.

**Comment by melcone** [comment]
I did 
![image](https://user-images.githubusercontent.com/98726565/154634113-0ab6cc86-a4fc-4829-979b-27a96f5145eb.png)

**Comment by GuessWhatBBQ** [comment]
You need to run the one I wrote here https://github.com/GuessWhatBBQ/FantechX9ThorDriver/issues/8#issuecomment-1043999004, and you could delete the other lines

**Comment by melcone** [comment]
It worked! Thanks for helping me, I appreciate it.

**Comment by GuessWhatBBQ** [comment]
This is probably the same problem being faced in #4 and #5 but no other info was provided for me to help.

The marketed names of the devices are the same but the models seem to be different. Some users reported getting it to work with a mouse branded with a completely different name. I think fantech just reuses their driver code and modifies the productids (but it's weird that they would change it for a product branded with the same name though).

**Comment by melcone** [comment]
At least we got to finally solve the problem to help the others who are facing the same problem.
