### ISSUE TITLE
DPI Levels Not Working

### ISSUE THREAD

**Issue by sapkotajeevan** [GuessWhatBBQ/FantechX9ThorDriver#9]
@theace1 made a fork for VX7. I got to open the UI but had issues with DPI.

The DPI Controls isn't working. Once I click "Apply", mouse is set to some high dpi and clicking dpi buttons doesn't change the dpi levels. 

Could you please tell what I may be missing here?

**Comment by GuessWhatBBQ** [comment]
My initial thoughts regarding this is that the commands for my X9 aren't compatible with your VX7, therefore you'll have to manually figure out the commands yourself and edit `driver_backend.py`.

So here's a general guide on how I reverse engineered the commands for setting DPI (or any functionality for that matter) for the mouse. I set up wireshark and began logging usb activity on the port connected to the mouse. I then used the official windows drivers (on a windows machine) to change the appropriate settings (DPI in your case) and observed the packets sent to the mouse. They tend to follow similar patterns so after poking around for a while you tend to figure out the packets needed. You'll have to do the same for the VX7. Fair warning this is tedious work.

**Comment by GuessWhatBBQ** [comment]
Did you have any luck using the code from this repo directly instead of the fork ?

**Comment by sapkotajeevan** [comment]
My mice is Fantech VX7 Crypto, so I had to use the fork. Fork in a sense only vendor code and product code is changed, everything else is similar. Ofcourse, if I use the original code aka for Thor it says my mice isn't detected.

**Comment by GuessWhatBBQ** [comment]
theace1 also made a change to line 169 on `driver_backend.py`, could you reverse that (set it back to 4800) and see if that solves the issue ?
